services:
  symfony:
    container_name: symfony_c_sae501
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./symfony:/var/www
    ports:
      - "9003:9003"
    working_dir: /var/www
    networks:
      - app_network
    command: sh -c "composer install && php-fpm"
    mem_limit: 2g

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - symfony

networks:
  app_network:
    driver: bridge