services:
  symfony:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .docker/.env
    volumes:
      - ./symfony:/var/www
    working_dir: /var/www
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - symfony

networks:
  app_network:
    driver: bridge