services:
  symfony:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: unless-stopped
    env_file:
      - .docker/.env
    volumes:
      - ./symfony:/var/www
    working_dir: /var/www
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - symfony

      #database:
    #image: postgres:17.2-alpine3.20
    #restart: unless-stopped
    #environment:
     # POSTGRES_PASSWORD: ${DB_PASSWORD}
      #POSTGRES_USER: ${DB_USERNAME}
      #POSTGRES_DB: ${DB_DATABASE}
    #volumes:
      #- ./.docker/db:/var/lib/postgresql/data:rw
    #networks:
     # - app_network

# Docker Networks
networks:
  app_network:
    driver: bridge