services:
  symfony:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .docker/.env
    volumes:
      - ./symfony:/var/www
      - ./.docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /var/www
    networks:
      - app_network
    command: sh -c "composer install && php-fpm"
    #command: "sleep infinity"
    mem_limit: 2g

  nginx:
    image: nginx:alpine
    volumes:
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./symfony:/var/www
    ports:
      - "8000:80"
    networks:
      - app_network
    depends_on:
      - symfony

networks:
  app_network:
    driver: bridge